url: 
baseurl: 

# Site settings
title: Blissful Web Development | Bay Area California | Software and web solutions
email: info@blissfulwebdev.com
description: "Commonsense Web Developerment, We'll simply your web and software situations. Softeware and web soultions. San Francisco, Bay Area. Wordpress, Custom Code, API integrations, Web Internationalizationm Website design"


# Team names, titles and social links
people:
- name: Nadav Somekh
  pic: nadavpic
  position: Co-Founder and Principal
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/nadav-somekh-46277254/
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty